# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'
steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    includePreviewVersions: true
    version: 3.0.100-preview6-012264
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: NuGetToolInstaller@1
- task: PowerShell@2
  inputs:
    filePath: 'pack.ps1'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'


